server:
  port: 8083

spring:
  application:
    name: report-service
  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
    username: postgres.kvubxhrfipcvlephrxam
    password: ${DB_PASSWORD:cadence_dev}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: ReportServiceHikariCP
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:cadence}
    password: ${RABBITMQ_PASSWORD:cadence_dev_pw}

management:
  endpoints:
    web:
      exposure:
        include: health
